//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace administracionCliente_Mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int PersonaNumero { get; set; }
        public string Nombre { get; set; }
        public string Cui { get; set; }
        public Nullable<int> SucursalNumero { get; set; }
    
        public virtual Sucursal Sucursal { get; set; }
    }
}
